# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\enroll.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(972, 638)
        Form.setMinimumSize(QtCore.QSize(972, 638))
        Form.setMaximumSize(QtCore.QSize(972, 638))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet(".QFrame#frame{border-image: url(:/img/enroll.png);}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pwdlineEdit = QtWidgets.QLineEdit(self.frame)
        self.pwdlineEdit.setGeometry(QtCore.QRect(510, 280, 251, 41))
        self.pwdlineEdit.setStyleSheet("font: 20 10pt \"阿里妈妈方圆体 VF Light\";\n"
"color:#000000;\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.pwdlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdlineEdit.setObjectName("pwdlineEdit")
        self.idlineEdit = QtWidgets.QLineEdit(self.frame)
        self.idlineEdit.setGeometry(QtCore.QRect(510, 230, 251, 31))
        self.idlineEdit.setStyleSheet("font: 20 10pt \"阿里妈妈方圆体 VF Light\";\n"
"color:#000000;\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.idlineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.idlineEdit.setObjectName("idlineEdit")
        self.enrollBtn = QtWidgets.QPushButton(self.frame)
        self.enrollBtn.setGeometry(QtCore.QRect(520, 470, 251, 31))
        self.enrollBtn.setStyleSheet("font: 20 10pt \"阿里妈妈方圆体 VF Light\";\n"
"color:#000000;\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.enrollBtn.setText("")
        self.enrollBtn.setObjectName("enrollBtn")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(590, 530, 91, 20))
        self.pushButton.setStyleSheet("font: 20 10pt \"阿里妈妈方圆体 VF Light\";\n"
"color:#000000;\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.yzmlineEdit = QtWidgets.QLineEdit(self.frame)
        self.yzmlineEdit.setGeometry(QtCore.QRect(530, 350, 201, 41))
        self.yzmlineEdit.setStyleSheet("font: 20 10pt \"阿里妈妈方圆体 VF Light\";\n"
"color:#000000;\n"
"border:none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.yzmlineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.yzmlineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.yzmlineEdit.setObjectName("yzmlineEdit")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(530, 410, 256, 39))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton.setStyleSheet("font: 12 8pt \"阿里妈妈方圆体 VF Thin\";")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_2.setStyleSheet("font: 12 8pt \"阿里妈妈方圆体 VF Thin\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.yzmlineEdit.setPlaceholderText(_translate("Form", "管理员注册填写"))
        self.radioButton.setText(_translate("Form", "普通用户"))
        self.radioButton_2.setText(_translate("Form", "管理员"))
import ui.img.image
